name: lint
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Run golangci-lint with reviewdog
      uses: reviewdog/action-golangci-lint@v1
      env:
        GO111MODULE: on
      with:
        golangci_lint_flags: "--enable-all --exclude-use-default=false"
        github_token: ${{ secrets.github_token }}
  

